### ISSUE TITLE
 "Unable to find a browser command" when using launchy in gitpod and other IDE's

### ISSUE THREAD

**Issue by MaxBrooks114** [copiousfreetime/launchy#124]
Hey so your gem is awesome and works perfectly in my mac's terminal, but when I try using it in the gitpod IDE or other IDE's I get this error:

`6: from bin/vgpop:6:in `<main>'
        5: from /workspace/vgpop/lib/vgpop/cli.rb:6:in `call'
        4: from /workspace/vgpop/lib/vgpop/cli.rb:51:in `menu'
        3: from /home/gitpod/.rvm/gems/ruby-2.6.0/gems/launchy-2.4.3/lib/launchy.rb:29:in `open'
        2: from /home/gitpod/.rvm/gems/ruby-2.6.0/gems/launchy-2.4.3/lib/launchy/applications/browser.rb:78:in `open'
        1: from /home/gitpod/.rvm/gems/ruby-2.6.0/gems/launchy-2.4.3/lib/launchy/applications/browser.rb:67:in `cmd_and_args'
/home/gitpod/.rvm/gems/ruby-2.6.0/gems/launchy-2.4.3/lib/launchy/applications/browser.rb:63:in `browser_cmdline': Unable to find a browser command. If this is unexpected, Please rerun with environment variable LAUNCHY_DEBUG=true or the '-d' commandline option and file a bug at https://github.com/copiousfreetime/launchy/issues/new (Launchy::CommandNotFoundError)`

The syntax I am using is `Launchy.open("#{url}")`

**Comment by copiousfreetime** [comment]
Hi @MaxBrooks114 Sorry I missed this.

I wouldn't expect launchy to work perfectly in something like gitpod. It looks like gitpod launches a cloud instance / docker container or something like that. And what launchy does is look for a commandline browser comand to run in order to display the webpage in your default browser. 

given that setup - if the gitpod environment has no browser application within it - I wouldn't expect launchy to work crorrectly. I'm not actually sure how launchy would work in that environment. And even if gitpod did have a browser application within it - I'm not show how it would launch and then display within the browser that you are using for gitpod.

I hope this helps.

**Comment by MaxBrooks114** [comment]
No worries, still appreciate the response. I had done a bit more searching and came to the same conclusion. I ended up just having the url displayed when using environments like those.

**Comment by copiousfreetime** [comment]
@MaxBrooks114 Sounds like a good plan. Thanks for the report in any case!
