### ISSUE TITLE
Suppress new proccess output

### ISSUE THREAD

**Issue by fuadsaud** [copiousfreetime/launchy#51]
Didn't find a way to suppress or redirect the STDOUT of new proccess.

**Comment by david-s-svedberg** [comment]
Still experiencing the issue in version 2.4.3 running on Ubuntu 14.04. As before, when executing Launchy.open(url) it opens the url in chrome but I get an output to stdout "Created new window in existing browser session."

**Comment by Onumis** [comment]
Same here, it's kinda annoying...

**Comment by copiousfreetime** [comment]
@david-s-svedberg @Onumis At the moment, launchy should be capturing all its stdout/stderr in the child process that launches chrome, and only displaying it if there was an exception. The relevant code is https://github.com/copiousfreetime/launchy/blob/master/lib/launchy/detect/runner.rb#L133-L141.

Feel free to put some debugging into there and see if the same thing occurs. The easy burn test would be to explicitly add `$stdout.close` and `$stderr.close` instead of saving them off to the side  in `StringIO` and see if that alleviates your issue.

If, when doing this, you no longer see `Created new window in existing browser session.` then there is something going on with the file descriptors that I'm unfamiliar with.

If you still see the output from chrome, then I'm not sure where that output is coming from or how it is getting to your console.

In any case, if someone has a Vagrant file handy that I can use to setup a system in the same manner you have, that would be helpful.
